version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directories:
      - /
      - /scripts/checks
    groups:
      babylonjs:
        patterns:
          - '@babylonjs/*'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directory: /deploy/docker
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
