package compatibility

import (
	"crypto/sha256"
	"fmt"
	"math"
	"sort"
	"strings"

	"baboreborn/backend/gameconfig"
)

// TuningValues references compiled constants, so ordinary tuning edits change the
// gameplay-profile fingerprint. Tests require this inventory to cover every constant.
func TuningValues() map[string]any {
	return map[string]any{
		"MovementAcceleration":               gameconfig.MovementAcceleration,
		"MovementFriction":                   gameconfig.MovementFriction,
		"MovementMaxSpeed":                   gameconfig.MovementMaxSpeed,
		"MovementRadius":                     gameconfig.MovementRadius,
		"MovementBounce":                     gameconfig.MovementBounce,
		"MovementClearance":                  gameconfig.MovementClearance,
		"MovementContactGap":                 gameconfig.MovementContactGap,
		"SmgFireIntervalSeconds":             gameconfig.SmgFireIntervalSeconds,
		"SmgEquipDelaySeconds":               gameconfig.SmgEquipDelaySeconds,
		"SmgDamage":                          gameconfig.SmgDamage,
		"SmgRecoil":                          gameconfig.SmgRecoil,
		"SmgMinSpreadDegrees":                gameconfig.SmgMinSpreadDegrees,
		"SmgMaxSpreadDegrees":                gameconfig.SmgMaxSpreadDegrees,
		"SmgSpreadPerShotDegrees":            gameconfig.SmgSpreadPerShotDegrees,
		"SmgSpreadRecoveryDegreesPerSecond":  gameconfig.SmgSpreadRecoveryDegreesPerSecond,
		"SmgCloseAimDistance":                gameconfig.SmgCloseAimDistance,
		"SmgVerticalSpreadScale":             gameconfig.SmgVerticalSpreadScale,
		"SmgMuzzleForward":                   gameconfig.SmgMuzzleForward,
		"SmgMuzzleRight":                     gameconfig.SmgMuzzleRight,
		"SmgMuzzleHeight":                    gameconfig.SmgMuzzleHeight,
		"ShotgunPellets":                     gameconfig.ShotgunPellets,
		"ShotgunPelletAngleDegrees":          gameconfig.ShotgunPelletAngleDegrees,
		"ShotgunSpreadDegrees":               gameconfig.ShotgunSpreadDegrees,
		"ShotgunRangeScale":                  gameconfig.ShotgunRangeScale,
		"ShotgunDamage":                      gameconfig.ShotgunDamage,
		"ShotgunRecoil":                      gameconfig.ShotgunRecoil,
		"ShotgunShells":                      gameconfig.ShotgunShells,
		"ShotgunReloadSeconds":               gameconfig.ShotgunReloadSeconds,
		"ShotgunFireIntervalSeconds":         gameconfig.ShotgunFireIntervalSeconds,
		"ShotgunMuzzleForward":               gameconfig.ShotgunMuzzleForward,
		"ShotgunMuzzleRight":                 gameconfig.ShotgunMuzzleRight,
		"ShieldCooldownSeconds":              gameconfig.ShieldCooldownSeconds,
		"ShieldProtectionSeconds":            gameconfig.ShieldProtectionSeconds,
		"ShieldInactiveTailSeconds":          gameconfig.ShieldInactiveTailSeconds,
		"ShieldDamageMultiplier":             gameconfig.ShieldDamageMultiplier,
		"KnivesCooldownSeconds":              gameconfig.KnivesCooldownSeconds,
		"KnivesRadius":                       gameconfig.KnivesRadius,
		"KnivesDamage":                       gameconfig.KnivesDamage,
		"KnivesVisualSeconds":                gameconfig.KnivesVisualSeconds,
		"ThrowingCooldownSeconds":            gameconfig.ThrowingCooldownSeconds,
		"ThrowingImpulse":                    gameconfig.ThrowingImpulse,
		"ThrowingMuzzleRight":                gameconfig.ThrowingMuzzleRight,
		"ThrowingMuzzleHeight":               gameconfig.ThrowingMuzzleHeight,
		"GrenadeSpawnCount":                  gameconfig.GrenadeSpawnCount,
		"GrenadeMaxCarry":                    gameconfig.GrenadeMaxCarry,
		"GrenadeHorizontalSpeed":             gameconfig.GrenadeHorizontalSpeed,
		"GrenadeVerticalSpeed":               gameconfig.GrenadeVerticalSpeed,
		"GrenadeFuseSeconds":                 gameconfig.GrenadeFuseSeconds,
		"GrenadeRadius":                      gameconfig.GrenadeRadius,
		"GrenadeDamage":                      gameconfig.GrenadeDamage,
		"GrenadeVisualRadius":                gameconfig.GrenadeVisualRadius,
		"MolotovSpawnCount":                  gameconfig.MolotovSpawnCount,
		"MolotovHorizontalSpeed":             gameconfig.MolotovHorizontalSpeed,
		"MolotovVerticalSpeed":               gameconfig.MolotovVerticalSpeed,
		"MolotovFlightSeconds":               gameconfig.MolotovFlightSeconds,
		"MolotovHitRadius":                   gameconfig.MolotovHitRadius,
		"MolotovImpactClearance":             gameconfig.MolotovImpactClearance,
		"MolotovReflectionScale":             gameconfig.MolotovReflectionScale,
		"MolotovScatterHorizontal":           gameconfig.MolotovScatterHorizontal,
		"MolotovScatterVertical":             gameconfig.MolotovScatterVertical,
		"MolotovFlameSeconds":                gameconfig.MolotovFlameSeconds,
		"MolotovDamageIntervalSeconds":       gameconfig.MolotovDamageIntervalSeconds,
		"MolotovDamageRadius":                gameconfig.MolotovDamageRadius,
		"MolotovDamage":                      gameconfig.MolotovDamage,
		"MolotovAttachRadius":                gameconfig.MolotovAttachRadius,
		"MolotovAttachSeconds":               gameconfig.MolotovAttachSeconds,
		"MolotovReattachDelaySeconds":        gameconfig.MolotovReattachDelaySeconds,
		"MolotovOwnerGraceSeconds":           gameconfig.MolotovOwnerGraceSeconds,
		"FlightGravity":                      gameconfig.FlightGravity,
		"FlightBounceRetention":              gameconfig.FlightBounceRetention,
		"FlightRestSpeed":                    gameconfig.FlightRestSpeed,
		"FlightRestHeight":                   gameconfig.FlightRestHeight,
		"FlightSurfaceClearance":             gameconfig.FlightSurfaceClearance,
		"FlightVelocityQuantization":         gameconfig.FlightVelocityQuantization,
		"PlayerMaxHealth":                    gameconfig.PlayerMaxHealth,
		"PickupsRadius":                      gameconfig.PickupsRadius,
		"PickupsHealthRestore":               gameconfig.PickupsHealthRestore,
		"PickupsWeaponSeconds":               gameconfig.PickupsWeaponSeconds,
		"PickupsGrenadeSeconds":              gameconfig.PickupsGrenadeSeconds,
		"PickupsHealthSeconds":               gameconfig.PickupsHealthSeconds,
		"PickupsDropSpeed":                   gameconfig.PickupsDropSpeed,
		"PickupsGuaranteedDropItems":         gameconfig.PickupsGuaranteedDropItems,
		"PickupsMaxItems":                    gameconfig.PickupsMaxItems,
		"PickupsInheritedVelocity":           gameconfig.PickupsInheritedVelocity,
		"PickupsDropTiltDegrees":             gameconfig.PickupsDropTiltDegrees,
		"DeathmatchScoreLimit":               gameconfig.DeathmatchScoreLimit,
		"DeathmatchTimeLimitSeconds":         gameconfig.DeathmatchTimeLimitSeconds,
		"DeathmatchRespawnSeconds":           gameconfig.DeathmatchRespawnSeconds,
		"DeathmatchEndSeconds":               gameconfig.DeathmatchEndSeconds,
		"DeathmatchForceRespawn":             gameconfig.DeathmatchForceRespawn,
		"DeathmatchSpawnProtectionSeconds":   gameconfig.DeathmatchSpawnProtectionSeconds,
		"DeathmatchSpawnInactiveTailSeconds": gameconfig.DeathmatchSpawnInactiveTailSeconds,
		"DeathmatchContactDelaySeconds":      gameconfig.DeathmatchContactDelaySeconds,
		"CameraHeight":                       gameconfig.CameraHeight,
		"CameraVerticalFovRadians":           gameconfig.CameraVerticalFovRadians,
		"CameraAspect":                       gameconfig.CameraAspect,
		"CameraNear":                         gameconfig.CameraNear,
		"CameraFar":                          gameconfig.CameraFar,
		"CameraFollow":                       gameconfig.CameraFollow,
		"CameraPlayerWeight":                 gameconfig.CameraPlayerWeight,
		"CameraAimWeight":                    gameconfig.CameraAimWeight,
		"CameraMarginX":                      gameconfig.CameraMarginX,
		"CameraMarginY":                      gameconfig.CameraMarginY,
		"CameraSpectatorHeight":              gameconfig.CameraSpectatorHeight,
		"CameraSpectatorSpeed":               gameconfig.CameraSpectatorSpeed,
		"CameraZoomScale":                    gameconfig.CameraZoomScale,
		"CameraMinZoom":                      gameconfig.CameraMinZoom,
		"DualFireIntervalSeconds":            gameconfig.DualFireIntervalSeconds,
		"DualDamage":                         gameconfig.DualDamage,
		"DualRecoil":                         gameconfig.DualRecoil,
		"DualMinSpreadDegrees":               gameconfig.DualMinSpreadDegrees,
		"DualMaxSpreadDegrees":               gameconfig.DualMaxSpreadDegrees,
		"ChainFireIntervalSeconds":           gameconfig.ChainFireIntervalSeconds,
		"ChainDamage":                        gameconfig.ChainDamage,
		"ChainRecoil":                        gameconfig.ChainRecoil,
		"ChainMinSpreadDegrees":              gameconfig.ChainMinSpreadDegrees,
		"ChainMaxSpreadDegrees":              gameconfig.ChainMaxSpreadDegrees,
		"ChainHeatPerShot":                   gameconfig.ChainHeatPerShot,
		"ChainRecovery":                      gameconfig.ChainRecovery,
		"ChainResumeAbove":                   gameconfig.ChainResumeAbove,
		"ChainPrecisionSpeed":                gameconfig.ChainPrecisionSpeed,
		"ChainPrecisionDivisor":              gameconfig.ChainPrecisionDivisor,
		"SniperFireIntervalSeconds":          gameconfig.SniperFireIntervalSeconds,
		"SniperDamage":                       gameconfig.SniperDamage,
		"SniperRecoil":                       gameconfig.SniperRecoil,
		"SniperNormalRays":                   gameconfig.SniperNormalRays,
		"SniperScopedRays":                   gameconfig.SniperScopedRays,
		"SniperScopeThreshold":               gameconfig.SniperScopeThreshold,
		"SniperMinHeight":                    gameconfig.SniperMinHeight,
		"SniperMaxHeight":                    gameconfig.SniperMaxHeight,
		"SniperAimScale":                     gameconfig.SniperAimScale,
		"SniperFollow":                       gameconfig.SniperFollow,
		"BazookaFireIntervalSeconds":         gameconfig.BazookaFireIntervalSeconds,
		"BazookaDamage":                      gameconfig.BazookaDamage,
		"BazookaRecoil":                      gameconfig.BazookaRecoil,
		"BazookaSpeed":                       gameconfig.BazookaSpeed,
		"BazookaMaxSpeed":                    gameconfig.BazookaMaxSpeed,
		"BazookaAcceleration":                gameconfig.BazookaAcceleration,
		"BazookaRemoteDelaySeconds":          gameconfig.BazookaRemoteDelaySeconds,
		"BazookaRadius":                      gameconfig.BazookaRadius,
		"BazookaLifetimeSeconds":             gameconfig.BazookaLifetimeSeconds,
		"PhotonFireIntervalSeconds":          gameconfig.PhotonFireIntervalSeconds,
		"PhotonDamage":                       gameconfig.PhotonDamage,
		"PhotonRecoil":                       gameconfig.PhotonRecoil,
		"PhotonChargeSeconds":                gameconfig.PhotonChargeSeconds,
		"PhotonDurationSeconds":              gameconfig.PhotonDurationSeconds,
		"PhotonPulseIntervalSeconds":         gameconfig.PhotonPulseIntervalSeconds,
		"PhotonPulseMultiplier":              gameconfig.PhotonPulseMultiplier,
		"PhotonPulseRadius":                  gameconfig.PhotonPulseRadius,
		"PhotonVerticalShift":                gameconfig.PhotonVerticalShift,
		"PhotonCoefficient":                  gameconfig.PhotonCoefficient,
		"PhotonHorizontalShift":              gameconfig.PhotonHorizontalShift,
		"PhotonDistanceMultiplier":           gameconfig.PhotonDistanceMultiplier,
		"FlamethrowerFireIntervalSeconds":    gameconfig.FlamethrowerFireIntervalSeconds,
		"FlamethrowerDamage":                 gameconfig.FlamethrowerDamage,
		"FlamethrowerRecoil":                 gameconfig.FlamethrowerRecoil,
		"FlamethrowerSpreadDegrees":          gameconfig.FlamethrowerSpreadDegrees,
		"FlamethrowerMaxRange":               gameconfig.FlamethrowerMaxRange,
		"FlamethrowerMinRange":               gameconfig.FlamethrowerMinRange,
		"FlamethrowerExpirationSeconds":      gameconfig.FlamethrowerExpirationSeconds,
		"FlamethrowerResetGapSeconds":        gameconfig.FlamethrowerResetGapSeconds,
		"FlamethrowerHitRadius":              gameconfig.FlamethrowerHitRadius,
		"MinibotCooldownSeconds":             gameconfig.MinibotCooldownSeconds,
		"MinibotLifetimeSeconds":             gameconfig.MinibotLifetimeSeconds,
		"MinibotRadius":                      gameconfig.MinibotRadius,
		"MinibotFireIntervalSeconds":         gameconfig.MinibotFireIntervalSeconds,
		"MinibotDamage":                      gameconfig.MinibotDamage,
		"MinibotSpawnOffset":                 gameconfig.MinibotSpawnOffset,
		"MinibotHeight":                      gameconfig.MinibotHeight,
		"DualMuzzleRight":                    gameconfig.DualMuzzleRight,
		"DualMuzzleForward":                  gameconfig.DualMuzzleForward,
		"DualMuzzleHeight":                   gameconfig.DualMuzzleHeight,
		"DualMuzzleRight2":                   gameconfig.DualMuzzleRight2,
		"DualMuzzleForward2":                 gameconfig.DualMuzzleForward2,
		"DualMuzzleHeight2":                  gameconfig.DualMuzzleHeight2,
		"ChainMuzzleRight":                   gameconfig.ChainMuzzleRight,
		"ChainMuzzleForward":                 gameconfig.ChainMuzzleForward,
		"ChainMuzzleHeight":                  gameconfig.ChainMuzzleHeight,
		"SniperMuzzleRight":                  gameconfig.SniperMuzzleRight,
		"SniperMuzzleForward":                gameconfig.SniperMuzzleForward,
		"SniperMuzzleHeight":                 gameconfig.SniperMuzzleHeight,
		"BazookaMuzzleRight":                 gameconfig.BazookaMuzzleRight,
		"BazookaMuzzleForward":               gameconfig.BazookaMuzzleForward,
		"BazookaMuzzleHeight":                gameconfig.BazookaMuzzleHeight,
		"PhotonMuzzleRight":                  gameconfig.PhotonMuzzleRight,
		"PhotonMuzzleForward":                gameconfig.PhotonMuzzleForward,
		"PhotonMuzzleHeight":                 gameconfig.PhotonMuzzleHeight,
		"FlamethrowerMuzzleRight":            gameconfig.FlamethrowerMuzzleRight,
		"FlamethrowerMuzzleForward":          gameconfig.FlamethrowerMuzzleForward,
		"FlamethrowerMuzzleHeight":           gameconfig.FlamethrowerMuzzleHeight,
		"MinibotSpreadDegrees":               gameconfig.MinibotSpreadDegrees,
		"MinibotMuzzleRight":                 gameconfig.MinibotMuzzleRight,
		"MinibotShotRange":                   gameconfig.MinibotShotRange,
	}
}

// GameProfile is an accidental-mismatch check, not proof that a server is trusted.
func GameProfile() string {
	values := TuningValues()
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var b strings.Builder
	for _, key := range keys {
		var value string
		switch n := values[key].(type) {
		case bool:
			value = "b0"
			if n {
				value = "b1"
			}
		case int:
			value = fmt.Sprintf("n%016x", math.Float64bits(float64(n)))
		case float64:
			value = fmt.Sprintf("n%016x", math.Float64bits(n))
		}
		fmt.Fprintf(&b, "%s=%s\n", key, value)
	}
	return fmt.Sprintf("%x", sha256.Sum256([]byte(b.String())))
}
