import { fromJson, toBinary } from '@bufbuild/protobuf';
import type { JsonValue } from '@bufbuild/protobuf';
import { DeliverySchema } from '../../src/network/generated/snapshot_pb';
import { POSITION_UNITS_PER_WORLD_UNIT, ANGLE_STEPS_PER_TURN } from '../../src/network/precision';
// Synthetic fixture encoder. Go-generated bytes provide the independent oracle.
export function encodeDelivery(value: unknown): string | Uint8Array {
  if (!value || typeof value !== 'object' || !('kind' in value) || value.kind !== 'state')
    return JSON.stringify(value);
  const frame = structuredClone(value) as unknown as { body: Record<string, unknown> };
  const s = frame.body;
  for (const player of (s.players ?? []) as { state?: Record<string, unknown> }[]) {
    const state = player.state;
    if (!state) continue;
    for (const key of ['x', 'y']) {
      if (typeof state[key] === 'number') {
        const scaled = state[key] * POSITION_UNITS_PER_WORLD_UNIT;
        // Go math.Round rounds halfway values away from zero.
        state[key] = Math.sign(scaled) * Math.round(Math.abs(scaled));
      }
    }
    if (typeof state.angle === 'number') {
      const turn = 2 * Math.PI;
      let angle = state.angle % turn;
      if (angle < 0) angle += turn;
      state.angle = Math.round((angle * ANGLE_STEPS_PER_TURN) / turn) % ANGLE_STEPS_PER_TURN;
    }
  }
  if (s.flags !== undefined) s.flags = { values: s.flags };
  const match = s.match as Record<string, unknown>;
  if (match.ranking !== undefined) match.ranking = { values: match.ranking };
  for (const key of ['items', 'projectiles']) {
    const v = s[key];
    if (v === null) throw new Error('Null entity group');
    if (v !== undefined) s[key] = Array.isArray(v) ? { values: v } : { ...v, delta: true };
  }
  if (s.local === null) delete s.local;
  function clean(v: unknown): unknown {
    if (v === null) throw new Error('Null protocol field');
    if (Array.isArray(v)) return v.map(clean);
    if (v && typeof v === 'object')
      return Object.fromEntries(
        Object.entries(v)
          .filter(([, x]) => x !== undefined)
          .map(([k, x]) => [k, clean(x)]),
      );
    return v;
  }
  return toBinary(DeliverySchema, fromJson(DeliverySchema, clean(frame) as JsonValue));
}
